#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:9000/eureka/
server:
  port: 9005
spring:
  application:
    name: cloud-feign
  profiles:
    active: dev

#健康监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

foo:
  bar: bar1
#链路跟踪
---
spring:
  sleuth:
    web:
      client:
        enabled: true #web开启sleuth功能
    sampler:
      probability: 1.0 # 将采样比例设置为 1.0，也就是全部都需要。默认是 0.1
  zipkin:
    base-url: http://localhost:9411/ # 指定了 Zipkin 服务器的地址
